### ISSUE TITLE
String resource not found

### ISSUE THREAD

**Issue by mrjameshamilton** [christiandeange/aaraar#12] opened 2024-09-04 15:42 UTC
Hi! We came across what seems to be a bug or if not, our misunderstanding of using/configuring `aaraar` and would appreciate some help. We have a project with the following:

* `lib1` which contains a string resource `lib1_hello_world`
* `lib2` which contains a class which references the string resource via `context.getString(com.example.test.lib1.R.string.lib1_hello_world)` and an implementation dependency on `lib1`
* `fatAar1` which is a library that has an `embed` dependency on both `lib1` and `lib2`

The problem occurs when using the library in an app, the resource is not found. I notice that there are R classes generated inside the fat aar and `int string lib1_hello_world 0x0` is in the `R.txt` file.

![image](https://github.com/user-attachments/assets/6f7d4866-8f9e-4515-979f-625663f8cce2)

When used in an app the resource is not found:

> android.content.res.Resources$NotFoundException: String resource ID #0x0

The string is in the app with the ID created during the app build:

![image](https://github.com/user-attachments/assets/f66515f6-b8e1-46bc-a7b8-3d72aa1a5b08)

I attach a sample project that reproduces the scenario. You can build it with `./gradlew :fatAar1:assemble` and then use the generated fat aar in an app project.

[demo-aaraar-issue.zip](https://github.com/user-attachments/files/16872807/demo-aaraar-issue.zip)

**Comment by christiandeange** [comment] 2024-11-12 04:14
Yeah, this does seem like a bug in aaraar. I think in `:fatAar1` and in any project that consumes that merged AAR, that string resource would be accessed via the namespace of `:fatAar1`, which would be `com.example.app.R.string.lib1_hello_world`. But obviously `:lib2` wouldn't be able to know about the namespace of the project(s) it's being embedded in, so you wouldn't be able to reference it from there...

I think `com.example.test.lib1.R.string.lib1_hello_world` just ends up being a dead file of sorts – it comes from `:lib1` and gets packaged with a bunch of default values, like this:

```java
package com.example.test.lib1;

public final class R {
  private R() {
  }

  public static final class string {
    public static int lib1_hello_world;

    private string() {
    }
  }
}
```

That explains why the test code things the resource id is 0, it's basically just an uninitialized int.

I think one thing that might resolve this (which would have to be done in the plugin itself, I reckon) would be to rewrite any reference to an `R` class to ensure that it's referencing the namespace of the project applying aaraar. It would have to be only the _usages_ because that `R.class` file shouldn't actually exist, I think.

**Comment by christiandeange** [comment] 2024-11-12 05:23
At the very least, I _think_ this can be mitigated for now by integrations by adding the following shading rules:

```groovy
aaraar {
    shading {
        createRule { configuration ->
            configuration.rename("**.R\$*", android.namespace + ".R\$@2")
            configuration.delete("**.R")
            configuration.delete("**.R\$*")
        }
    }
}
```

This should have the two-pronged effect of:
- Normalizing all namespaced `R` class usage to use the namespace of the project applying the aaraar plugin
- Deleting any actual `R` classes so that they can be properly generated by the project consuming the merged aar file

By the way, your example project in the zip file was _super_ helpful for reproducing the issue – thank you for that!

**Closed as completed** 2024-12-11 08:09 UTC

**Comment by christiandeange** [comment] 2024-12-11 21:46
Version `0.0.18` has been published which should contain a fix for this!

**Comment by mrjameshamilton** [comment] 2024-12-12 10:41
Thanks @christiandeange !
